# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mohammad/Octopos/from_zephyr/octopos_hardware/Octopos_MailBox_3Writer-1Reader/Octopos_MailBox_v1/Octopos_MailBox_v1.srcs/sources_1/imports/sources_1/ip/mailbox_0/mailbox_0.xci
# IP: The module: 'mailbox_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mohammad/Octopos/from_zephyr/octopos_hardware/Octopos_MailBox_3Writer-1Reader/Octopos_MailBox_v1/Octopos_MailBox_v1.srcs/sources_1/imports/sources_1/ip/mailbox_0/mailbox_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mailbox_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mohammad/Octopos/from_zephyr/octopos_hardware/Octopos_MailBox_3Writer-1Reader/Octopos_MailBox_v1/Octopos_MailBox_v1.srcs/sources_1/imports/sources_1/ip/mailbox_0/mailbox_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mailbox_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/mohammad/Octopos/from_zephyr/octopos_hardware/Octopos_MailBox_3Writer-1Reader/Octopos_MailBox_v1/Octopos_MailBox_v1.srcs/sources_1/imports/sources_1/ip/mailbox_0/mailbox_0.xci
# IP: The module: 'mailbox_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mohammad/Octopos/from_zephyr/octopos_hardware/Octopos_MailBox_3Writer-1Reader/Octopos_MailBox_v1/Octopos_MailBox_v1.srcs/sources_1/imports/sources_1/ip/mailbox_0/mailbox_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mailbox_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/mohammad/Octopos/from_zephyr/octopos_hardware/Octopos_MailBox_3Writer-1Reader/Octopos_MailBox_v1/Octopos_MailBox_v1.srcs/sources_1/imports/sources_1/ip/mailbox_0/mailbox_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mailbox_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
