num_of_ports = 4;
manyWriter_OneReader =0;

version = 'v1_0'
suffix = ''
if(manyWriter_OneReader):
    suffix = "%dWriter_1Reader" % num_of_ports
else:
    suffix = "1Writer_%dReader" % num_of_ports

f = open("sample.v","w+");
#for i in 
#range(0,10):
#    f.write("this is a line %d\n" % i);

f.write('`timescale 1 ns / 1 ps\n')
f.write('\tmodule Octopos_MailBox_%s_%s #\n'% (suffix,version))

f.write('\t//Parameters\n')
f.write('\t(\n') # parameter def start
f.write('\t\t// Parameters of Axi contrl Buses Interfaces\n') # comment
f.write('\t\tparameter integer C_S_ctrl_AXI_DATA_WIDTH	= 32,\n')
f.write('\t\tparameter integer C_S_ctrl_AXI_ADDR_WIDTH	= 4\n')
f.write('\t)\n') # parameter def end

f.write('\t//Ports\n')
f.write('\t(\n') # Ports def start
f.write('\t\t// MailBox Main Signals\n') # comment
f.write('\t\tinput wire S_CLK,\n')
f.write('\t\tinput wire S_ARESETN,\n')
for i in range(0,num_of_ports):
    f.write('\t\t// Ctrl%d AXI port\n' % i) # comment
    f.write('\t\tinput wire  s_ctrl%d_axi_aclk,\n' % i)
    f.write('\t\tinput wire  s_ctrl%d_axi_aresetn,\n' % i)
    f.write('\t\tinput wire [C_S_ctrl_AXI_ADDR_WIDTH-1 : 0] s_ctrl%d_axi_awaddr,\n' % i)
    f.write('\t\tinput wire [2 : 0] s_ctrl%d_axi_awprot,\n' % i)
    f.write('\t\tinput wire  s_ctrl%d_axi_awvalid,\n' % i)
    f.write('\t\toutput wire  s_ctrl%d_axi_awready,\n' % i)
    f.write('\t\tinput wire [C_S_ctrl_AXI_DATA_WIDTH-1 : 0] s_ctrl%d_axi_wdata,\n' % i)
    f.write('\t\tinput wire [(C_S_ctrl_AXI_DATA_WIDTH/8)-1 : 0] s_ctrl%d_axi_wstrb,\n' % i)
    f.write('\t\tinput wire  s_ctrl%d_axi_wvalid,\n' % i)
    f.write('\t\toutput wire  s_ctrl%d_axi_wready,\n' % i)
    f.write('\t\toutput wire [1 : 0] s_ctrl%d_axi_bresp,\n' % i)
    f.write('\t\toutput wire  s_ctrl%d_axi_bvalid,\n' % i)
    f.write('\t\tinput wire  s_ctrl%d_axi_bready,\n' % i)
    f.write('\t\tinput wire [C_S_ctrl_AXI_ADDR_WIDTH-1 : 0] s_ctrl%d_axi_araddr,\n' % i)
    f.write('\t\tinput wire [2 : 0] s_ctrl%d_axi_arprot,\n' % i)
    f.write('\t\tinput wire  s_ctrl%d_axi_arvalid,\n' % i)
    f.write('\t\toutput wire  s_ctrl%d_axi_arready,\n' % i)
    f.write('\t\toutput wire [C_S_ctrl_AXI_DATA_WIDTH-1 : 0] s_ctrl%d_axi_rdata,\n' % i)
    f.write('\t\toutput wire [1 : 0] s_ctrl%d_axi_rresp,\n' % i)
    f.write('\t\toutput wire  s_ctrl%d_axi_rvalid,\n' % i)
    f.write('\t\tinput wire  s_ctrl%d_axi_rready,\n' % i)
f.write('\t\t// Ctrl%s AXI port\n' % '_fixed') # comment
f.write('\t\tinput wire  s_ctrl%s_axi_aclk,\n' % '_fixed')
f.write('\t\tinput wire  s_ctrl%s_axi_aresetn,\n' % '_fixed')
f.write('\t\tinput wire [C_S_ctrl_AXI_ADDR_WIDTH-1 : 0] s_ctrl%s_axi_awaddr,\n' % '_fixed')
f.write('\t\tinput wire [2 : 0] s_ctrl%s_axi_awprot,\n' % '_fixed')
f.write('\t\tinput wire  s_ctrl%s_axi_awvalid,\n' % '_fixed')
f.write('\t\toutput wire  s_ctrl%s_axi_awready,\n' % '_fixed')
f.write('\t\tinput wire [C_S_ctrl_AXI_DATA_WIDTH-1 : 0] s_ctrl%s_axi_wdata,\n' % '_fixed')
f.write('\t\tinput wire [(C_S_ctrl_AXI_DATA_WIDTH/8)-1 : 0] s_ctrl%s_axi_wstrb,\n' % '_fixed')
f.write('\t\tinput wire  s_ctrl%s_axi_wvalid,\n' % '_fixed')
f.write('\t\toutput wire  s_ctrl%s_axi_wready,\n' % '_fixed')
f.write('\t\toutput wire [1 : 0] s_ctrl%s_axi_bresp,\n' % '_fixed')
f.write('\t\toutput wire  s_ctrl%s_axi_bvalid,\n' % '_fixed')
f.write('\t\tinput wire  s_ctrl%s_axi_bready,\n' % '_fixed')
f.write('\t\tinput wire [C_S_ctrl_AXI_ADDR_WIDTH-1 : 0] s_ctrl%s_axi_araddr,\n' % '_fixed')
f.write('\t\tinput wire [2 : 0] s_ctrl%s_axi_arprot,\n' % '_fixed')
f.write('\t\tinput wire  s_ctrl%s_axi_arvalid,\n' % '_fixed')
f.write('\t\toutput wire  s_ctrl%s_axi_arready,\n' % '_fixed')
f.write('\t\toutput wire [C_S_ctrl_AXI_DATA_WIDTH-1 : 0] s_ctrl%s_axi_rdata,\n' % '_fixed')
f.write('\t\toutput wire [1 : 0] s_ctrl%s_axi_rresp,\n' % '_fixed')
f.write('\t\toutput wire  s_ctrl%s_axi_rvalid,\n' % '_fixed')
f.write('\t\tinput wire  s_ctrl%s_axi_rready,\n' % '_fixed')    
for i in range(0,num_of_ports):
    f.write('\t\t// data%d AXI port\n' % i) # comment
    f.write('\t\tinput wire S0_data%d_AXI_ACLK,\n' % i)
    f.write('\t\tinput wire S0_data%d_AXI_ARESETN,\n' % i)
    f.write('\t\tinput wire [31 : 0] S0_data%d_AXI_AWADDR,\n' % i)
    f.write('\t\tinput wire S0_data%d_AXI_AWVALID,\n' % i)
    f.write('\t\toutput wire S0_data%d_AXI_AWREADY,\n' % i)
    f.write('\t\tinput wire [31 : 0] S0_data%d_AXI_WDATA,\n' % i)
    f.write('\t\tinput wire [3 : 0] S0_data%d_AXI_WSTRB,\n' % i)
    f.write('\t\tinput wire S0_data%d_AXI_WVALID,\n' % i)
    f.write('\t\toutput wire S0_data%d_AXI_WREADY,\n' % i)
    f.write('\t\toutput wire [1 : 0] S0_data%d_AXI_BRESP,\n' % i)
    f.write('\t\toutput wire S0_data%d_AXI_BVALID,\n' % i)
    f.write('\t\tinput wire S0_data%d_AXI_BREADY,\n' % i)
    f.write('\t\tinput wire [31 : 0] S0_data%d_AXI_ARADDR,\n' % i)
    f.write('\t\tinput wire S0_data%d_AXI_ARVALID,\n' % i)
    f.write('\t\toutput wire S0_data%d_AXI_ARREADY,\n' % i)
    f.write('\t\toutput wire [31 : 0] S0_data%d_AXI_RDATA,\n' % i)
    f.write('\t\toutput wire [1 : 0] S0_data%d_AXI_RRESP,\n' % i)
    f.write('\t\toutput wire S0_data%d_AXI_RVALID,\n' % i)
    f.write('\t\tinput wire S0_data%d_AXI_RREADY,\n' % i)
f.write('\t\t// data%s AXI port\n' % '_fixed') # comment
f.write('\t\tinput wire S1_data%s_AXI_ACLK,\n' % '_fixed')
f.write('\t\tinput wire S1_data%s_AXI_ARESETN,\n' % '_fixed')
f.write('\t\tinput wire [31 : 0] S1_data%s_AXI_AWADDR,\n' % '_fixed')
f.write('\t\tinput wire S1_data%s_AXI_AWVALID,\n' % '_fixed')
f.write('\t\toutput wire S1_data%s_AXI_AWREADY,\n' % '_fixed')
f.write('\t\tinput wire [31 : 0] S1_data%s_AXI_WDATA,\n' % '_fixed')
f.write('\t\tinput wire [3 : 0] S1_data%s_AXI_WSTRB,\n' % '_fixed')
f.write('\t\tinput wire S1_data%s_AXI_WVALID,\n' % '_fixed')
f.write('\t\toutput wire S1_data%s_AXI_WREADY,\n' % '_fixed')
f.write('\t\toutput wire [1 : 0] S1_data%s_AXI_BRESP,\n' % '_fixed')
f.write('\t\toutput wire S1_data%s_AXI_BVALID,\n' % '_fixed')
f.write('\t\tinput wire S1_data%s_AXI_BREADY,\n' % '_fixed')
f.write('\t\tinput wire [31 : 0] S1_data%s_AXI_ARADDR,\n' % '_fixed')
f.write('\t\tinput wire S1_data%s_AXI_ARVALID,\n' % '_fixed')
f.write('\t\toutput wire S1_data%s_AXI_ARREADY,\n' % '_fixed')
f.write('\t\toutput wire [31 : 0] S1_data%s_AXI_RDATA,\n' % '_fixed')
f.write('\t\toutput wire [1 : 0] S1_data%s_AXI_RRESP,\n' % '_fixed')
f.write('\t\toutput wire S1_data%s_AXI_RVALID,\n' % '_fixed')
f.write('\t\tinput wire S1_data%s_AXI_RREADY,\n' % '_fixed')

f.write('\t\t// Interrupt lines\n') # comment
for i in range(0,num_of_ports):
    f.write('\t\toutput wire Interrupt_%d,\n' % i) 
    f.write('\t\toutput wire Interrupt_ctrl%d,\n' % i)
f.write('\t\toutput wire Interrupt_fixed,\n') 
f.write('\t\toutput wire Interrupt_ctrl_fixed\n') 

f.write('\t);//Ports def end\n') # Ports def end

#Id defenitions
f.write('\t//Constant defenitions\n')
for i in range(0,num_of_ports):
    f.write('\t`define ID%d 8\'d%d\n' % (i,i) )
f.write('\t`define YIELD_ID 8\'d255\n' )
f.write('\t`define ID%s %s\n' % ('_FIXED', '9\'b111111111') )
f.write('\t`define INFINITY 12\'hFFF\n')
f.write('\t`define STACK_SIZE 16\n')
f.write('\t`define TIMER_MAX 10000000\n')
f.write('\tinteger i;\n')
f.write('\t//System registers (FlipFlops) defenitions\n')#comment
f.write('\treg [31:0] state_reg;\n')
f.write('\treg [7:0] owner_id;\n')
f.write('\treg [11:0] time_out;\n')
f.write('\treg [11:0] limit;\n')
f.write('\treg write_req_latched;\n')
f.write('\treg stack_req_latched;\n')
f.write('\treg timer_req_latched;\n')

f.write('\treg limit_req_latched;\n')
f.write('\treg [7:0] stack_pointer;\n')
f.write('\treg [31:0] stack_memory [`STACK_SIZE:0];\n')
f.write('\treg [31:0] timer_counter;\n' )

f.write('\treg Octopos_resetn;\n')

f.write('\t//System wires(Some defined as reg to be used in always blocks)defenitions\n')#comment
f.write('\treg [31:0] write_state_value;\n')
f.write('\treg [7:0]  write_state_owner_id;\n')
f.write('\treg [11:0] write_state_time_out;\n')
f.write('\treg [11:0] write_state_limit;\n')
f.write('\treg [11:0] next_time_out;\n')
f.write('\treg [11:0] next_limit;\n')
f.write('\treg write_req;\n')
f.write('\treg write_req_valid;\n')
f.write('\treg write_req_reset;\n')
f.write('\treg stack_req;\n')
f.write('\treg stack_req_reset;\n')
f.write('\treg timer_req;\n')
f.write('\treg timer_req_reset;\n')
f.write('\treg limit_req;\n')
f.write('\treg limit_req_reset;\n')
for i in range(0,num_of_ports):
    f.write('\twire [31:0] s_ctrl%d_write_state_value;\n' % i) 
    f.write('\twire  s_ctrl%d_write_req;\n' % i)
f.write('\twire [31:0] s_ctrl%s_write_state_value;\n' % '_fixed') 
f.write('\twire  s_ctrl%s_write_req;\n' % '_fixed')

f.write('\t//Internal mailbox programable side signals\n')#comment
f.write('\treg S0_data_AXI_ACLK;\n')
f.write('\treg S0_data_AXI_ARESETN;\n')
f.write('\treg [31 : 0] S0_data_AXI_AWADDR;\n')
f.write('\treg S0_data_AXI_AWVALID;\n')
f.write('\twire S0_data_AXI_AWREADY;\n')
f.write('\treg [31 : 0] S0_data_AXI_WDATA;\n')
f.write('\treg [3 : 0] S0_data_AXI_WSTRB;\n')
f.write('\treg S0_data_AXI_WVALID;\n')
f.write('\twire S0_data_AXI_WREADY;\n')
f.write('\twire [1 : 0] S0_data_AXI_BRESP;\n')
f.write('\twire S0_data_AXI_BVALID;\n')
f.write('\treg S0_data_AXI_BREADY;\n')
f.write('\treg [31 : 0] S0_data_AXI_ARADDR;\n')
f.write('\treg S0_data_AXI_ARVALID;\n')
f.write('\twire S0_data_AXI_ARREADY;\n')
f.write('\twire [31 : 0] S0_data_AXI_RDATA;\n')
f.write('\twire [1 : 0] S0_data_AXI_RRESP;\n')
f.write('\twire S0_data_AXI_RVALID;\n')
f.write('\treg S0_data_AXI_RREADY;\n')
f.write('\twire Interrupt_S0;\n')

f.write('\t//Temporary reg signals for data output wires\n')#comment
f.write('\t//to use them in always blocks\n')#comment
for i in range(0,num_of_ports):
    f.write('\t// Temp regs for port %d\n' %i)
    f.write('\treg S0_data%d_AXI_AWREADY_reg;\n' % i)
    f.write('\treg S0_data%d_AXI_WREADY_reg;\n' % i)
    f.write('\treg [1 : 0] S0_data%d_AXI_BRESP_reg;\n' % i)
    f.write('\treg S0_data%d_AXI_BVALID_reg;\n' % i)
    f.write('\treg S0_data%d_AXI_ARREADY_reg;\n' % i)
    f.write('\treg [31 : 0] S0_data%d_AXI_RDATA_reg;\n' % i)
    f.write('\treg [1 : 0] S0_data%d_AXI_RRESP_reg;\n' % i)
    f.write('\treg S0_data%d_AXI_RVALID_reg;\n' % i)
#    f.write('\treg S0_data%d_AXI_RVALID_reg;\n' % i)
    f.write('\treg Interrupt%d_reg;\n' % i)

f.write('\t//Connect output wires to temporary regs \n')#comment
f.write('\tassign clk = S_CLK;\n')
f.write('\tassign resetn = S_ARESETN;;\n')
	
for i in range(0,num_of_ports):
    f.write('\t// Assignment for port %d\n' %i)
    f.write('\tassign S0_data%d_AXI_WREADY = S0_data%d_AXI_WREADY_reg;\n' % (i,i))
    f.write('\tassign S0_data%d_AXI_BRESP = S0_data%d_AXI_BRESP_reg;\n' % (i,i))
    f.write('\tassign S0_data%d_AXI_BVALID = S0_data%d_AXI_BVALID_reg;\n' % (i,i))
    f.write('\tassign S0_data%d_AXI_AWREADY = S0_data%d_AXI_AWREADY_reg;\n' % (i,i))
    f.write('\tassign S0_data%d_AXI_ARREADY = S0_data%d_AXI_ARREADY_reg;\n' % (i,i))
    f.write('\tassign S0_data%d_AXI_RDATA = S0_data%d_AXI_RDATA_reg;\n' % (i,i))
    f.write('\tassign S0_data%d_AXI_RRESP = S0_data%d_AXI_RRESP_reg;\n' % (i,i))
    f.write('\tassign S0_data%d_AXI_RVALID = S0_data%d_AXI_RVALID_reg;\n' % (i,i))
    f.write('\tassign Interrupt_%d = Interrupt%d_reg;\n' % (i,i))

f.write('\n\t//Multiplexer for Mailbox programable port \n')#comment
f.write('\talways @(*)\n')
f.write('\tbegin\n')
f.write('\t\tcase(owner_id)\n')
for i in range(0,num_of_ports):
    f.write('\t\t\t`ID%d: begin\n' %i)
# Mailbox input signals
    f.write('\t\t\t\t// Mailbox input signals\n') #comment
    f.write('\t\t\t\tS0_data_AXI_ACLK = S0_data%d_AXI_ACLK;\n' % i )
    f.write('\t\t\t\tS0_data_AXI_ARESETN = S0_data%d_AXI_ARESETN;\n' % i )
    f.write('\t\t\t\tS0_data_AXI_AWADDR = S0_data%d_AXI_AWADDR;\n' % i )
    f.write('\t\t\t\tS0_data_AXI_AWVALID = S0_data%d_AXI_AWVALID;\n' % i )
    f.write('\t\t\t\tS0_data_AXI_WDATA = S0_data%d_AXI_WDATA;\n' % i )
    f.write('\t\t\t\tS0_data_AXI_WSTRB = S0_data%d_AXI_WSTRB;\n' % i )
    f.write('\t\t\t\tS0_data_AXI_WVALID = S0_data%d_AXI_WVALID;\n' % i )
    f.write('\t\t\t\tS0_data_AXI_BREADY = S0_data%d_AXI_BREADY;\n' % i )
    f.write('\t\t\t\tS0_data_AXI_ARADDR = S0_data%d_AXI_ARADDR;\n' % i )
    f.write('\t\t\t\tS0_data_AXI_ARVALID = S0_data%d_AXI_ARVALID;\n' % i )
    f.write('\t\t\t\tS0_data_AXI_RREADY = S0_data%d_AXI_RREADY;\n' % i )
# Mailbox output signals        
    f.write('\t\t\t\t//Mailbox output signals\n') #comment    
    f.write('\t\t\t\t////Outputs for current ID\n') #comment    
    f.write('\t\t\t\tS0_data%d_AXI_RVALID_reg = S0_data_AXI_RVALID;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_RRESP_reg = S0_data_AXI_RRESP;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_RDATA_reg = S0_data_AXI_RDATA;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_ARREADY_reg = S0_data_AXI_ARREADY;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_BVALID_reg = S0_data_AXI_BVALID;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_BRESP_reg = S0_data_AXI_BRESP;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_WREADY_reg = S0_data_AXI_WREADY;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_AWREADY_reg = S0_data_AXI_AWREADY;\n' % i )
    f.write('\t\t\t\tInterrupt%d_reg = Interrupt_S0;\n' % i )
    f.write('\t\t\t\t////Outputs for other IDs\n') #comment
    for j in range(0,num_of_ports):
        if( i!=j):
            f.write('\t\t\t\t//////Outputs for  ID%d\n' % j) #comment
            f.write('\t\t\t\tS0_data%d_AXI_RVALID_reg = 0;\n' % j )
            f.write('\t\t\t\tS0_data%d_AXI_RRESP_reg = 0;\n' % j )
            f.write('\t\t\t\tS0_data%d_AXI_RDATA_reg = 0;\n' % j )
            f.write('\t\t\t\tS0_data%d_AXI_ARREADY_reg = 0;\n' % j )
            f.write('\t\t\t\tS0_data%d_AXI_BVALID_reg = 0;\n' % j )
            f.write('\t\t\t\tS0_data%d_AXI_BRESP_reg = 0;\n' % j )
            f.write('\t\t\t\tS0_data%d_AXI_WREADY_reg = 0;\n' % j )
            f.write('\t\t\t\tS0_data%d_AXI_AWREADY_reg = 0;\n' % j )
            f.write('\t\t\t\tInterrupt%d_reg = 0;\n' % j )
    f.write('\t\t\tend\n')
f.write('\t\t\tdefault: begin\n')
f.write('\t\t\t\t// Mailbox input signals\n') #comment	
f.write('\t\t\t\tS0_data_AXI_ACLK = 0;\n')
f.write('\t\t\t\tS0_data_AXI_ARESETN = 0;\n')
f.write('\t\t\t\tS0_data_AXI_AWADDR = 0;\n')
f.write('\t\t\t\tS0_data_AXI_AWVALID = 0;\n')
f.write('\t\t\t\tS0_data_AXI_WDATA = 0;\n')
f.write('\t\t\t\tS0_data_AXI_WSTRB = 0;\n')
f.write('\t\t\t\tS0_data_AXI_WVALID = 0;\n')
f.write('\t\t\t\tS0_data_AXI_BREADY = 0;\n')
f.write('\t\t\t\tS0_data_AXI_ARADDR = 0;\n')
f.write('\t\t\t\tS0_data_AXI_ARVALID = 0;\n')
f.write('\t\t\t\tS0_data_AXI_RREADY = 0; \n')
f.write('\t\t\t\t//Mailbox output signals\n') #comment    
f.write('\t\t\t\t////Outputs for All IDs\n') #comment
for i in range(0,num_of_ports):
# Mailbox output signals       
    f.write('\t\t\t\t////Outputs for ID%d\n' % i) #comment     
    f.write('\t\t\t\tS0_data%d_AXI_RVALID_reg = 0;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_RRESP_reg = 0;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_RDATA_reg = 0;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_ARREADY_reg = 0;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_BVALID_reg = 0;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_BRESP_reg = 0;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_WREADY_reg = 0;\n' % i )
    f.write('\t\t\t\tS0_data%d_AXI_AWREADY_reg = 0;\n' % i )
    f.write('\t\t\t\tInterrupt%d_reg = 0;\n' % i )	
f.write('\t\t\tend\n')	
f.write('\t\tendcase\n')
f.write('\tend//for always @(*)\n')		

#Internal Mailbox instantiation
f.write('\n\t//Internal MailBox Instantiation\n')
f.write('\tmailbox_0 mb0 (\n')
f.write('\t\t.S0_AXI_ACLK(S0_data_AXI_ACLK),        // input wire S0_AXI_ACLK\n')
f.write('\t\t.S0_AXI_ARESETN(S0_data_AXI_ARESETN & Octopos_resetn),  // input wire S0_AXI_ARESETN\n')
f.write('\t\t.S0_AXI_AWADDR(S0_data_AXI_AWADDR),    // input wire [31 : 0] S0_AXI_AWADDR\n')
f.write('\t\t.S0_AXI_AWVALID(S0_data_AXI_AWVALID),  // input wire S0_AXI_AWVALID\n')
f.write('\t\t.S0_AXI_AWREADY(S0_data_AXI_AWREADY),  // output wire S0_AXI_AWREADY\n')
f.write('\t\t.S0_AXI_WDATA(S0_data_AXI_WDATA),      // input wire [31 : 0] S0_AXI_WDATA\n')
f.write('\t\t.S0_AXI_WSTRB(S0_data_AXI_WSTRB),      // input wire [3 : 0] S0_AXI_WSTRB\n')
f.write('\t\t.S0_AXI_WVALID(S0_data_AXI_WVALID),    // input wire S0_AXI_WVALID\n')
f.write('\t\t.S0_AXI_WREADY(S0_data_AXI_WREADY),    // output wire S0_AXI_WREADY\n')
f.write('\t\t.S0_AXI_BRESP(S0_data_AXI_BRESP),      // output wire [1 : 0] S0_AXI_BRESP\n')
f.write('\t\t.S0_AXI_BVALID(S0_data_AXI_BVALID),    // output wire S0_AXI_BVALID\n')
f.write('\t\t.S0_AXI_BREADY(S0_data_AXI_BREADY),    // input wire S0_AXI_BREADY\n')
f.write('\t\t.S0_AXI_ARADDR(S0_data_AXI_ARADDR),    // input wire [31 : 0] S0_AXI_ARADDR\n')
f.write('\t\t.S0_AXI_ARVALID(S0_data_AXI_ARVALID),  // input wire S0_AXI_ARVALID\n')
f.write('\t\t.S0_AXI_ARREADY(S0_data_AXI_ARREADY),  // output wire S0_AXI_ARREADY\n')
f.write('\t\t.S0_AXI_RDATA(S0_data_AXI_RDATA),      // output wire [31 : 0] S0_AXI_RDATA\n')
f.write('\t\t.S0_AXI_RRESP(S0_data_AXI_RRESP),      // output wire [1 : 0] S0_AXI_RRESP\n')
f.write('\t\t.S0_AXI_RVALID(S0_data_AXI_RVALID),    // output wire S0_AXI_RVALID\n')
f.write('\t\t.S0_AXI_RREADY(S0_data_AXI_RREADY),    // input wire S0_AXI_RREADY\n')
f.write('\t\t.S1_AXI_ACLK(S1_data_fixed_AXI_ACLK),        // input wire S1_AXI_ACLK\n')
f.write('\t\t.S1_AXI_ARESETN(S1_data_fixed_AXI_ARESETN & Octopos_resetn),  // input wire S1_AXI_ARESETN\n')
f.write('\t\t.S1_AXI_AWADDR(S1_data_fixed_AXI_AWADDR),    // input wire [31 : 0] S1_AXI_AWADDR\n')
f.write('\t\t.S1_AXI_AWVALID(S1_data_fixed_AXI_AWVALID),  // input wire S1_AXI_AWVALID\n')
f.write('\t\t.S1_AXI_AWREADY(S1_data_fixed_AXI_AWREADY),  // output wire S1_AXI_AWREADY\n')
f.write('\t\t.S1_AXI_WDATA(S1_data_fixed_AXI_WDATA),      // input wire [31 : 0] S1_AXI_WDATA\n')
f.write('\t\t.S1_AXI_WSTRB(S1_data_fixed_AXI_WSTRB),      // input wire [3 : 0] S1_AXI_WSTRB\n')
f.write('\t\t.S1_AXI_WVALID(S1_data_fixed_AXI_WVALID),    // input wire S1_AXI_WVALID\n')
f.write('\t\t.S1_AXI_WREADY(S1_data_fixed_AXI_WREADY),    // output wire S1_AXI_WREADY\n')
f.write('\t\t.S1_AXI_BRESP(S1_data_fixed_AXI_BRESP),      // output wire [1 : 0] S1_AXI_BRESP\n')
f.write('\t\t.S1_AXI_BVALID(S1_data_fixed_AXI_BVALID),    // output wire S1_AXI_BVALID\n')
f.write('\t\t.S1_AXI_BREADY(S1_data_fixed_AXI_BREADY),    // input wire S1_AXI_BREADY\n')
f.write('\t\t.S1_AXI_ARADDR(S1_data_fixed_AXI_ARADDR),    // input wire [31 : 0] S1_AXI_ARADDR\n')
f.write('\t\t.S1_AXI_ARVALID(S1_data_fixed_AXI_ARVALID),  // input wire S1_AXI_ARVALID\n')
f.write('\t\t.S1_AXI_ARREADY(S1_data_fixed_AXI_ARREADY),  // output wire S1_AXI_ARREADY\n')
f.write('\t\t.S1_AXI_RDATA(S1_data_fixed_AXI_RDATA),      // output wire [31 : 0] S1_AXI_RDATA\n')
f.write('\t\t.S1_AXI_RRESP(S1_data_fixed_AXI_RRESP),      // output wire [1 : 0] S1_AXI_RRESP\n')
f.write('\t\t.S1_AXI_RVALID(S1_data_fixed_AXI_RVALID),    // output wire S1_AXI_RVALID\n')
f.write('\t\t.S1_AXI_RREADY(S1_data_fixed_AXI_RREADY),    // input wire S1_AXI_RREADY\n')
f.write('\t\t.Interrupt_0(Interrupt_S0),        // output wire Interrupt_0\n')
f.write('\t\t.Interrupt_1(Interrupt_fixed)         // output wire Interrupt_1\n')
f.write('\t);\n')
	
f.write('\t//Control AXI buses instantiation\n')
for i in range(0,num_of_ports):    
    f.write('\t//Control AXI bus%d instantiation\n' % i)
    f.write('\tOctopos_MailBox_ctrl_AXI # (\n')
    f.write('\t\t.C_S_AXI_DATA_WIDTH(C_S_ctrl_AXI_DATA_WIDTH),\n')
    f.write('\t\t.C_S_AXI_ADDR_WIDTH(C_S_ctrl_AXI_ADDR_WIDTH)\n')
    f.write('\t) Octopos_MailBox_ctrl_AXI_ctrl%d_instance (\n' % i)
    f.write('\t\t.S_AXI_ACLK(s_ctrl%d_axi_aclk),\n' % i )
    f.write('\t\t.S_AXI_ARESETN(s_ctrl%d_axi_aresetn),\n' % i )
    f.write('\t\t.S_AXI_AWADDR(s_ctrl%d_axi_awaddr),\n' % i )
    f.write('\t\t.S_AXI_AWPROT(s_ctrl%d_axi_awprot),\n' % i )
    f.write('\t\t.S_AXI_AWVALID(s_ctrl%d_axi_awvalid),\n' % i )
    f.write('\t\t.S_AXI_AWREADY(s_ctrl%d_axi_awready),\n' % i )
    f.write('\t\t.S_AXI_WDATA(s_ctrl%d_axi_wdata),\n' % i )
    f.write('\t\t.S_AXI_WSTRB(s_ctrl%d_axi_wstrb),\n' % i )
    f.write('\t\t.S_AXI_WVALID(s_ctrl%d_axi_wvalid),\n' % i )
    f.write('\t\t.S_AXI_WREADY(s_ctrl%d_axi_wready),\n' % i )
    f.write('\t\t.S_AXI_BRESP(s_ctrl%d_axi_bresp),\n' % i )
    f.write('\t\t.S_AXI_BVALID(s_ctrl%d_axi_bvalid),\n' % i )
    f.write('\t\t.S_AXI_BREADY(s_ctrl%d_axi_bready),\n' % i )
    f.write('\t\t.S_AXI_ARADDR(s_ctrl%d_axi_araddr),\n' % i )
    f.write('\t\t.S_AXI_ARPROT(s_ctrl%d_axi_arprot),\n' % i )
    f.write('\t\t.S_AXI_ARVALID(s_ctrl%d_axi_arvalid),\n' % i )
    f.write('\t\t.S_AXI_ARREADY(s_ctrl%d_axi_arready),\n' % i )
    f.write('\t\t.S_AXI_RDATA(s_ctrl%d_axi_rdata),\n' % i )
    f.write('\t\t.S_AXI_RRESP(s_ctrl%d_axi_rresp),\n' % i )
    f.write('\t\t.S_AXI_RVALID(s_ctrl%d_axi_rvalid),\n' % i )
    f.write('\t\t.S_AXI_RREADY(s_ctrl%d_axi_rready),\n' % i )
    f.write('\t\t.S_WRITE_REQ(s_ctrl%d_write_req),\n' % i )
    f.write('\t\t.S_WRITE_STATE_VALUE(s_ctrl%d_write_state_value),\n' % i )
    f.write('\t\t.S_ID({1\'b0,`ID%d}),\n' % i)
    f.write('\t\t.S_SYSTEM_STATE_REG(state_reg),\n')
    f.write('\t\t.S_INTERRUPT(Interrupt_ctrl%d)\n' % i)
    f.write('\t);\n')

f.write('\t//Control AXI bus%s instantiation\n' % '_fixed')
f.write('\tOctopos_MailBox_ctrl_AXI # (\n')
f.write('\t\t.C_S_AXI_DATA_WIDTH(C_S_ctrl_AXI_DATA_WIDTH),\n')
f.write('\t\t.C_S_AXI_ADDR_WIDTH(C_S_ctrl_AXI_ADDR_WIDTH)\n')
f.write('\t) Octopos_MailBox_ctrl_AXI_ctrl%s_instance (\n' % '_fixed')
f.write('\t\t.S_AXI_ACLK(s_ctrl%s_axi_aclk),\n' % '_fixed' )
f.write('\t\t.S_AXI_ARESETN(s_ctrl%s_axi_aresetn),\n' % '_fixed' )
f.write('\t\t.S_AXI_AWADDR(s_ctrl%s_axi_awaddr),\n' % '_fixed' )
f.write('\t\t.S_AXI_AWPROT(s_ctrl%s_axi_awprot),\n' % '_fixed' )
f.write('\t\t.S_AXI_AWVALID(s_ctrl%s_axi_awvalid),\n' % '_fixed' )
f.write('\t\t.S_AXI_AWREADY(s_ctrl%s_axi_awready),\n' % '_fixed' )
f.write('\t\t.S_AXI_WDATA(s_ctrl%s_axi_wdata),\n' % '_fixed' )
f.write('\t\t.S_AXI_WSTRB(s_ctrl%s_axi_wstrb),\n' % '_fixed' )
f.write('\t\t.S_AXI_WVALID(s_ctrl%s_axi_wvalid),\n' % '_fixed' )
f.write('\t\t.S_AXI_WREADY(s_ctrl%s_axi_wready),\n' % '_fixed' )
f.write('\t\t.S_AXI_BRESP(s_ctrl%s_axi_bresp),\n' % '_fixed' )
f.write('\t\t.S_AXI_BVALID(s_ctrl%s_axi_bvalid),\n' % '_fixed' )
f.write('\t\t.S_AXI_BREADY(s_ctrl%s_axi_bready),\n' % '_fixed' )
f.write('\t\t.S_AXI_ARADDR(s_ctrl%s_axi_araddr),\n' % '_fixed' )
f.write('\t\t.S_AXI_ARPROT(s_ctrl%s_axi_arprot),\n' % '_fixed' )
f.write('\t\t.S_AXI_ARVALID(s_ctrl%s_axi_arvalid),\n' % '_fixed' )
f.write('\t\t.S_AXI_ARREADY(s_ctrl%s_axi_arready),\n' % '_fixed' )
f.write('\t\t.S_AXI_RDATA(s_ctrl%s_axi_rdata),\n' % '_fixed' )
f.write('\t\t.S_AXI_RRESP(s_ctrl%s_axi_rresp),\n' % '_fixed' )
f.write('\t\t.S_AXI_RVALID(s_ctrl%s_axi_rvalid),\n' % '_fixed' )
f.write('\t\t.S_AXI_RREADY(s_ctrl%s_axi_rready),\n' % '_fixed' )
f.write('\t\t.S_WRITE_REQ(s_ctrl%s_write_req),\n' % '_fixed' )
f.write('\t\t.S_WRITE_STATE_VALUE(s_ctrl%s_write_state_value),\n' % '_fixed' )
f.write('\t\t.S_ID({1\'b0,`ID%s}),\n' % '_FIXED')
f.write('\t\t.S_SYSTEM_STATE_REG(state_reg),\n')
f.write('\t\t.S_INTERRUPT(Interrupt_ctrl%s)\n' % '_fixed')
f.write('\t);\n')

f.write('\n\t//Octopos Mailbox Main logic\n\n ') #comment
f.write('\n\t//Combinational logic\n\n ') #comment
f.write('\t//State register break down\n ') #comment
f.write('\talways @(*)\n')
f.write('\tbegin\n')
f.write('\t\t//For System State register\n ') #comment
f.write('\t\towner_id = state_reg[31:24];\n')
f.write('\t\tlimit = state_reg[23:12];\n')
f.write('\t\ttime_out = state_reg[11:0];\n')
f.write('\t\t//For to be writtern register\n ') #comment
f.write('\t\twrite_state_owner_id = write_state_value[31:24];\n')
f.write('\t\twrite_state_limit = write_state_value[23:12];\n')
f.write('\t\twrite_state_time_out = write_state_value[11:0];\n')
f.write('\tend\n')

f.write('\t//Multiplexer for write_state_value and write_req \n ') #comment
f.write('\talways @(*)\n')
f.write('\tbegin\n')
f.write('\t\tcase(owner_id)\n')
for i in range(0,num_of_ports):
    f.write('\t\t\t`ID%d: begin\n' % i)
    f.write('\t\t\t\twrite_state_value = s_ctrl%d_write_state_value;\n' % i)
    f.write('\t\t\t\twrite_req = s_ctrl%d_write_req;\n' % i)
    f.write('\t\t\tend\n')
f.write('\t\t\tdefault: begin\n')
f.write('\t\t\t\twrite_state_value = 32\'b0;\n')
f.write('\t\t\t\twrite_req = 1\'b0;\n')			
f.write('\t\t\tend\n')
f.write('\t\tendcase\n')
f.write('\tend\n')

f.write('\t//Reset generation for req signal latches \n ') #comment
f.write('\talways @(*)\n')
f.write('\tbegin\n')
f.write('\t\tstack_req_reset = stack_req_latched;\n')
f.write('\t\twrite_req_reset = (!stack_req_latched) & write_req_latched;\n')
f.write('\t\tlimit_req_reset = (!stack_req_latched) & (!write_req_latched) & limit_req_latched;\n')
f.write('\t\ttimer_req_reset = (!stack_req_latched) & (!write_req_latched) & (!limit_req_latched) & timer_req_latched;\n')
f.write('\tend\n')

f.write('\t//Generate a signal to know when we need to pop the stack \n ') #comment
f.write('\talways @(*)\n')
f.write('\tbegin\n')
f.write('\t\tif( (limit == 8\'b0) || (time_out == 12\'b0) || ( (write_req == 1\'b1) && (write_state_owner_id == `YIELD_ID) ) )\n')
f.write('\t\t\tstack_req = 1\'b1;\n')
f.write('\t\telse\n')
f.write('\t\t\tstack_req = 1\'b0;\n')
f.write('\tend\n')

f.write('\t//Generate a signal to know when outside ctrl channel can rewrite the state reg \n ') #comment
f.write('\talways @(*)\n')
f.write('\tbegin\n')
f.write('\t\tif( (write_req == 1\'b1)&& (write_state_limit < limit) &&  (write_state_limit != 0) &&(write_state_time_out < time_out) &&(write_state_time_out != 0) && (write_state_owner_id != `YIELD_ID)  )\n')
f.write('\t\t\twrite_req_valid = 1\'b1;\n')
f.write('\t\telse\n')
f.write('\t\t\twrite_req_valid = 1\'b0;\n')
f.write('\tend\n')

f.write('\t//Calculate the normal next values for time_out and limit  \n ') #comment
f.write('\talways @(*)\n')
f.write('\tbegin\n')
f.write('\t\tif( limit == 0 )\n')
f.write('\t\t\tnext_limit = 1\'b0;\n')
f.write('\t\telse if ( limit == `INFINITY)\n')
f.write('\t\t\tnext_limit  = `INFINITY;\n')
f.write('\t\telse\n')
f.write('\t\t\tnext_limit  = limit - 1\'b1;\n')
f.write('\tend\n')

f.write('\talways @(*)\n')
f.write('\tbegin\n')
f.write('\t\tif( time_out == 0 )\n')
f.write('\t\t\tnext_time_out = 1\'b0;\n')
f.write('\t\telse if ( time_out == `INFINITY)\n')
f.write('\t\t\tnext_time_out  = `INFINITY;\n')
f.write('\t\telse\n')
f.write('\t\t\tnext_time_out  = time_out - 1\'b1;\n')
f.write('\tend\n\n')

f.write('\n\t//Generate timer_req and limit_req signals\n ') #comment
if(manyWriter_OneReader == 1):
    f.write('\talways @(*)\n')
    f.write('\tbegin\n')
    f.write('\t\tif((S1_data_fixed_AXI_ARADDR[8:0] == 8\'h08) && (S1_data_fixed_AXI_ARREADY ==1\'b1))\n')
    f.write('\t\t\tlimit_req = 1\'b1;\n')
    f.write('\t\telse\n')
    f.write('\t\t\tlimit_req = 1\'b0;\n')
    f.write('\tend\n')
else:
    f.write('\talways @(*)\n')
    f.write('\tbegin\n')
    f.write('\t\tif((S0_data_AXI_ARADDR[8:0] == 8\'h08) && (S0_data_AXI_ARREADY ==1\'b1))\n')
    f.write('\t\t\tlimit_req = 1\'b1;\n')
    f.write('\t\telse\n')
    f.write('\t\t\tlimit_req = 1\'b0;\n')
    f.write('\tend\n')

f.write('\talways @(*)\n')
f.write('\tbegin\n')
f.write('\t\tif(timer_counter == 32\'b0)\n')
f.write('\t\t\ttimer_req = 1\'b1;\n')
f.write('\t\telse\n')
f.write('\t\t\ttimer_req = 1\'b0;\n')
f.write('\tend\n')

f.write('\n\t//Sequential logic\n\n ') #comment
f.write('\t//FlipFlops for Multiplexer Chain selectors latched signals\n') #comment
f.write('\talways @( posedge clk )\n')
f.write('\tbegin\n')
f.write('\t\tif( resetn == 1\'b0 )\n')
f.write('\t\t  begin\n')
f.write('\t\t    stack_req_latched <= 1\'b0;\n')
f.write('\t\t\twrite_req_latched <= 1\'b0; \n')
f.write('\t\t\tlimit_req_latched <= 1\'b0;\n')
f.write('\t\t\ttimer_req_latched <= 1\'b0;\n')
f.write('\t\t\t\n')
f.write('\t\t  end\n')
f.write('\t\telse\n')
f.write('\t\t  begin\n')
f.write('\t\t  \n')
f.write('\t\t\tif(stack_req_reset == 1\'b1)\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t    stack_req_latched <= 1\'b0;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\telse\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t    if(stack_req_latched == 1\'b0)\n')
f.write('\t\t\t\t\tstack_req_latched <= stack_req;\n')
f.write('\t\t\t\telse\n')
f.write('\t\t\t\t\tstack_req_latched <=  stack_req_latched;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\t  \n')
f.write('\t\t\tif(write_req_reset == 1\'b1)\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t    write_req_latched <= 1\'b0;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\telse\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t    if(write_req_latched == 1\'b0)\n')
f.write('\t\t\t\t\twrite_req_latched <= write_req_valid;\n')
f.write('\t\t\t\telse\n')
f.write('\t\t\t\t\twrite_req_latched <=  write_req_latched;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\t  \n')
f.write('\t\t\tif(limit_req_reset == 1\'b1)\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t    limit_req_latched <= 1\'b0;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\telse\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t    if(limit_req_latched == 1\'b0)\n')
f.write('\t\t\t\t\tlimit_req_latched <= limit_req;\n')
f.write('\t\t\t\telse\n')
f.write('\t\t\t\t\tlimit_req_latched <=  limit_req_latched;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\t  \n')
f.write('\t\t\tif(timer_req_reset == 1\'b1)\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t    timer_req_latched <= 1\'b0;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\telse\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t    if(timer_req_latched == 1\'b0)\n')
f.write('\t\t\t\t\ttimer_req_latched <= timer_req;\n')
f.write('\t\t\t\telse\n')
f.write('\t\t\t\t\ttimer_req_latched <=  timer_req_latched;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\t\t\n')
f.write('\t\t  end\n')
f.write('\tend\n')

f.write('\t//FlipFlops for the main state_reg and stack ( and the main Multiplexer chain)\n')
f.write('\talways @( posedge clk )\n')
f.write('\tbegin\n')
f.write('\t\tif( resetn == 1\'b0 )\n')
f.write('\t\t  begin\n')
f.write('\t\t    // on reset give the infinit amount of limits to the first enclave\n')
f.write('\t\t    state_reg <= { `ID0 , `INFINITY, `INFINITY};\n')
f.write('\t\t\t//stack regs\n')
f.write('\t\t\tstack_pointer <= 0;\n')
f.write('\t\t\tfor (i = 0; i < `STACK_SIZE; i = i +1) begin\n')
f.write('\t\t\t\tstack_memory[i] <= 32\'b0;\n')
f.write('\t\t\tend\n')
f.write('\t\t\tOctopos_resetn <= 1\'b1;\n')
f.write('\t\t  end\n')
f.write('\t\telse\n')
f.write('\t\t  begin\n')
f.write('\t\t\tif(stack_req_latched == 1\'b1)\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t    //pop the stack and load the data into the state_reg, if it is a yield give the remaining limits to the parent\n')
f.write('\t\t\t    if( (write_req == 1\'b1) && (write_state_owner_id == `YIELD_ID) )\n')
f.write('\t\t\t\t  begin\n')
#f.write('\t\t\t\t    state_reg <= {stack_memory[stack_pointer -1][31:24] , stack_memory[stack_pointer -1][23:12] + limit , stack_memory[stack_pointer -1][11:0]  +time_out};\n')
f.write('\t\t\t\t\tif( (stack_memory[stack_pointer -1][23:12] == `INFINITY)&&(stack_memory[stack_pointer -1][11:0]==`INFINITY)) \n')
f.write('\t\t\t\t\t	state_reg <= {stack_memory[stack_pointer -1][31:24] , stack_memory[stack_pointer -1][23:12]  , stack_memory[stack_pointer -1][11:0] };\n')
f.write('\t\t\t\t\telse if (stack_memory[stack_pointer -1][23:12] == `INFINITY)\n')
f.write('\t\t\t\t\t	state_reg <= {stack_memory[stack_pointer -1][31:24] , stack_memory[stack_pointer -1][23:12] , stack_memory[stack_pointer -1][11:0]  +time_out};\n')
f.write('\t\t\t\t\telse if (stack_memory[stack_pointer -1][11:0]==`INFINITY)\n')
f.write('\t\t\t\t\t	state_reg <= {stack_memory[stack_pointer -1][31:24] , stack_memory[stack_pointer -1][23:12] + limit , stack_memory[stack_pointer -1][11:0]};\n')
f.write('\t\t\t\t\telse\n')
f.write('\t\t\t\t\t	state_reg <= {stack_memory[stack_pointer -1][31:24] , stack_memory[stack_pointer -1][23:12] + limit , stack_memory[stack_pointer -1][11:0]  +time_out};\n')
f.write('\t\t\t\t  end\n')
f.write('\t\t\t\telse\n')
f.write('\t\t\t\t  begin\n')
f.write('\t\t\t\t\tstate_reg <= stack_memory[stack_pointer -1 ];\n')
f.write('\t\t\t\t  end\n')
f.write('\t\t\t\tstack_pointer <= stack_pointer - 1;  \n')
f.write('\t\t\t\tOctopos_resetn <= 1\'b0;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\telse if (write_req_latched == 1\'b1)\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t    //push the parent remaining permissions to the stack\n')
#f.write('\t\t\t\tstack_memory[ stack_pointer ] <= { owner_id , limit - write_state_limit , time_out - write_state_time_out};\n')
f.write('\t\t\t\tif( (limit == `INFINITY) && ( time_out == `INFINITY) ) \n')
f.write('\t\t\t\t\tstack_memory[ stack_pointer ] <= { owner_id , limit , time_out };\n')
f.write('\t\t\t\telse if (limit == `INFINITY)\n')
f.write('\t\t\t\t\tstack_memory[ stack_pointer ] <= { owner_id , limit  , time_out - write_state_time_out};	\n')
f.write('\t\t\t\telse if ( time_out == `INFINITY)\n')
f.write('\t\t\t\t\tstack_memory[ stack_pointer ] <= { owner_id , limit - write_state_limit , time_out};\n')
f.write('\t\t\t\telse\n')	
f.write('\t\t\t\t\tstack_memory[ stack_pointer ] <= { owner_id , limit - write_state_limit , time_out - write_state_time_out};\n')
f.write('\t\t\t\tstack_pointer <= stack_pointer + 1;\n')
f.write('\t\t\t\t//update the state_reg with new value\n')
f.write('\t\t\t\tstate_reg <= write_state_value;\n')
f.write('\t\t\t\tOctopos_resetn <= 1\'b0;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\telse if (limit_req_latched == 1\'b1)\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t\tstate_reg <= {owner_id, next_limit , time_out};\n')
f.write('\t\t\t\tOctopos_resetn <= 1\'b1;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\telse if (timer_req_latched == 1\'b1)\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t\tstate_reg <= {owner_id , limit , next_time_out};\n')
f.write('\t\t\t\tOctopos_resetn <= 1\'b1;\n')
f.write('\t\t\t  end\n')
f.write('\t\t\telse\n')
f.write('\t\t\t  begin\n')
f.write('\t\t\t\tstate_reg <= state_reg;\n')
f.write('\t\t\t\tOctopos_resetn <= 1\'b1;\n')
f.write('\t\t\t  end\n')
f.write('\t\t  end\n')
f.write('\tend\n')

f.write('\t//TIMER\n') #comment
f.write('\talways @( posedge clk )\n')
f.write('\tbegin\n')
f.write('\t\tif( resetn == 1\'b0 )\n')
f.write('\t\t  begin\n')
f.write('\t\t    timer_counter <= `TIMER_MAX;\n')
f.write('\t\t  end\n')
f.write('\t\telse\n')
f.write('\t\t  begin\n')
f.write('\t\t\tif(timer_counter == 32\'b0)\n')
f.write('\t\t\t\ttimer_counter <= `TIMER_MAX;\n')
f.write('\t\t\telse\n')
f.write('\t\t\t\ttimer_counter <= timer_counter - 1;\n')
f.write('\t\t  end\n')
f.write('\tend\t \n')
f.write('\tendmodule\n') # module end
