sudo umount $1/oss/src/octopos/arch
sudo umount $1/oss/src/octopos/include
sudo umount $1/oss/src/octopos/os
sudo umount $1/os_bootloader/src/octopos/arch
sudo umount $1/os_bootloader/src/octopos/include
sudo umount $1/os_bootloader/src/octopos/bootloader
sudo umount $1/os_bootloader/src/octopos/os
sudo umount $1/storage/src/octopos/storage
sudo umount $1/storage/src/octopos/include
sudo umount $1/storage/src/octopos/arch
sudo umount $1/storage_bootloader/src/octopos/arch
sudo umount $1/storage_bootloader/src/octopos/include
sudo umount $1/storage_bootloader/src/octopos/bootloader
sudo umount $1/storage_bootloader/src/octopos/storage
sudo umount $1/keyboard/src/octopos/keyboard
sudo umount $1/keyboard/src/octopos/include
sudo umount $1/keyboard/src/octopos/arch
sudo umount $1/keyboard_bootloader/src/octopos/include
sudo umount $1/keyboard_bootloader/src/octopos/arch
sudo umount $1/keyboard_bootloader/src/octopos/bootloader
sudo umount $1/serialout/src/octopos/serial_out
sudo umount $1/serialout/src/octopos/include
sudo umount $1/serialout/src/octopos/arch
sudo umount $1/serialout_bootloader/src/octopos/include
sudo umount $1/serialout_bootloader/src/octopos/arch
sudo umount $1/serialout_bootloader/src/octopos/bootloader
sudo umount $1/enclave0/src/octopos/arch
sudo umount $1/enclave0/src/octopos/include
sudo umount $1/enclave0/src/octopos/runtime
sudo umount $1/enclave0/src/octopos/application/ipc_s
sudo umount $1/enclave0/src/octopos/application/ipc_r
sudo umount $1/enclave0/src/octopos/application/sec_i
sudo umount $1/enclave0/src/octopos/application/sec_login
sudo umount $1/enclave0/src/octopos/application/sim_loop
sudo umount $1/enclave0/src/octopos/application/fs_test
sudo umount $1/enclave0_bootloader/src/octopos/arch
sudo umount $1/enclave0_bootloader/src/octopos/include
sudo umount $1/enclave0_bootloader/src/octopos/bootloader
sudo umount $1/enclave1/src/octopos/arch
sudo umount $1/enclave1/src/octopos/include
sudo umount $1/enclave1/src/octopos/runtime
sudo umount $1/enclave1/src/octopos/application/ipc_s
sudo umount $1/enclave1/src/octopos/application/ipc_r
sudo umount $1/enclave1/src/octopos/application/sec_i
sudo umount $1/enclave1/src/octopos/application/sec_login
sudo umount $1/enclave1/src/octopos/application/sim_loop
sudo umount $1/enclave1/src/octopos/application/fs_test
sudo umount $1/enclave1_bootloader/src/octopos/arch
sudo umount $1/enclave1_bootloader/src/octopos/include
sudo umount $1/enclave1_bootloader/src/octopos/bootloader
sudo umount $1/enclave0/src/octopos/utils/network
sudo umount $1/enclave1/src/octopos/utils/network
sudo umount $1/enclave0/src/octopos/application/socket_client
sudo umount $1/enclave1/src/octopos/application/socket_client
sudo umount $1/network_bootloader/src/octopos/bootloader
sudo umount $1/network_bootloader/src/octopos/include
sudo umount $1/network_bootloader/src/octopos/arch
sudo umount $1/network/src/octopos/network
sudo umount $1/network/src/octopos/util/network
sudo umount $1/network/src/octopos/arch
sudo umount $1/network/src/octopos/include