rm -r $1/oss/src/octopos/arch
rm -r $1/oss/src/octopos/include
rm -r $1/oss/src/octopos/os
rm -r $1/os_bootloader/src/octopos/arch
rm -r $1/os_bootloader/src/octopos/include
rm -r $1/os_bootloader/src/octopos/bootloader
rm -r $1/os_bootloader/src/octopos/os
rm -r $1/storage_bootloader/src/octopos/arch
rm -r $1/storage_bootloader/src/octopos/include
rm -r $1/storage_bootloader/src/octopos/bootloader
rm -r $1/storage_bootloader/src/octopos/storage
rm -r $1/storage/src/octopos/storage
rm -r $1/storage/src/octopos/include
rm -r $1/storage/src/octopos/arch
rm -r $1/keyboard/src/octopos/keyboard
rm -r $1/keyboard/src/octopos/include
rm -r $1/keyboard/src/octopos/arch
rm -r $1/keyboard_bootloader/src/octopos/include
rm -r $1/keyboard_bootloader/src/octopos/arch
rm -r $1/keyboard_bootloader/src/octopos/bootloader
rm -r $1/serialout/src/octopos/serial_out
rm -r $1/serialout/src/octopos/include
rm -r $1/serialout/src/octopos/arch
rm -r $1/serialout_bootloader/src/octopos/include
rm -r $1/serialout_bootloader/src/octopos/arch
rm -r $1/serialout_bootloader/src/octopos/bootloader
rm -r $1/enclave0/src/octopos/arch
rm -r $1/enclave0/src/octopos/include
rm -r $1/enclave0/src/octopos/runtime
rm -r $1/enclave0/src/octopos/application/ipc_s
rm -r $1/enclave0/src/octopos/application/ipc_r
rm -r $1/enclave0/src/octopos/application/sec_i
rm -r $1/enclave0/src/octopos/application/sec_login
rm -r $1/enclave0/src/octopos/application/sim_loop
rm -r $1/enclave0/src/octopos/application/fs_test
rm -r $1/enclave0/src/octopos/application/socket_client
rm -r $1/enclave0/src/octopos/utils/network
rm -r $1/enclave0_bootloader/src/octopos/arch
rm -r $1/enclave0_bootloader/src/octopos/include
rm -r $1/enclave0_bootloader/src/octopos/bootloader
rm -r $1/enclave1/src/octopos/arch
rm -r $1/enclave1/src/octopos/include
rm -r $1/enclave1/src/octopos/runtime
rm -r $1/enclave1/src/octopos/application/ipc_s
rm -r $1/enclave1/src/octopos/application/ipc_r
rm -r $1/enclave1/src/octopos/application/sec_i
rm -r $1/enclave1/src/octopos/application/sec_login
rm -r $1/enclave1/src/octopos/application/sim_loop
rm -r $1/enclave1/src/octopos/application/fs_test
rm -r $1/enclave1/src/octopos/application/socket_client
rm -r $1/enclave1/src/octopos/utils/network
rm -r $1/enclave1_bootloader/src/octopos/arch
rm -r $1/enclave1_bootloader/src/octopos/include
rm -r $1/enclave1_bootloader/src/octopos/bootloader
rm -r $1/network_bootloader/src/octopos/bootloader
rm -r $1/network_bootloader/src/octopos/arch
rm -r $1/network_bootloader/src/octopos/include
rm -r $1/network/src/octopos/network
rm -r $1/network/src/octopos/util
rm -r $1/network/src/octopos/arch
rm -r $1/network/src/octopos/include